### ISSUE TITLE
HD icons, unneeded double loading.

### ISSUE THREAD

**Issue by ImNotSatan** [Nepeta/Notifica#10]
`
UIButton *iconButton = ntfGetIconButtonFromHCV(headerContentView);
    
    //if (![self.ntfId isEqualToString:self.widgetHost.appBundleID]) {
    //    self.ntfId = self.widgetHost.appBundleID;
        if ([configExperimental hdIcons]) {
            if (self.widgetHost && self.widgetHost.appBundleID) {
                UIImage *icon = [[[%c(SBApplicationController) sharedInstance] applicationWithBundleIdentifier: self.widgetHost.appBundleID] icon: nil imageWithFormat: 0];
                if (icon) {
                    [iconButton setImage:icon forState:UIControlStateNormal];
                }
            }
        }`

Should be
```
	UIButton *iconButton;
    
    //if (![self.ntfId isEqualToString:self.widgetHost.appBundleID]) {
    //    self.ntfId = self.widgetHost.appBundleID;
        if ([configExperimental hdIcons]) {
            if (self.widgetHost && self.widgetHost.appBundleID) {
                UIImage *icon = [[[%c(SBApplicationController) sharedInstance] applicationWithBundleIdentifier: self.widgetHost.appBundleID] icon: nil imageWithFormat: 0];
                if (icon) {
                    [iconButton setImage:icon forState:UIControlStateNormal];
                }
            }
        }
        else
        {
              *iconButton = ntfGetIconButtonFromHCV(headerContentView);
        }
```

**Comment by Nepeta** [comment]
Fixed in a different way.
