### ISSUE TITLE
Widget content color not working correctly

### ISSUE THREAD

**Issue by ImNotSatan** [Nepeta/Notifica#11]
[Screenshot 1](https://prnt.sc/msqx1q)
Here you can see that the text doesn't dispaly properly.

The text is set to white (#FFFFFF)
And the widget of siri recents blinks white (sometimes) and then hides the text.
Siri shortcuts has just all black text.

**Comment by tomaszpoliszuk** [comment]
Additional widgets with the same problem:

![batteries](https://user-images.githubusercontent.com/7104816/53731179-3ead7c80-3e7a-11e9-9ef4-4e1c6eff70a2.png)
![surge](https://user-images.githubusercontent.com/7104816/53731180-3ead7c80-3e7a-11e9-936b-08fbea85032f.png)
![weather](https://user-images.githubusercontent.com/7104816/53731181-3ead7c80-3e7a-11e9-8ac7-16c9dad7eb80.png)
![widget calendar](https://user-images.githubusercontent.com/7104816/53731182-3f461300-3e7a-11e9-8260-e313e2f10d83.png)

**Comment by tomaszpoliszuk** [comment]
Temporary partially fix:

use Dune from https://skitty.xyz/repo/ - it fixes problem on:

- weather
- batteries
- shortcuts
- widget-calendar

Surge is still not visible, not sure how it works for Siri Suggestions

**Comment by Nepeta** [comment]
Fixed.
