### ISSUE TITLE
Themed icons aren’t taking effect on some stacked notifications and they’re enlarged 

### ISSUE THREAD

**Issue by zyan910** [Nepeta/Notifica#13]
![e46b4100-86d8-47d6-9e9a-d47a96221372](https://user-images.githubusercontent.com/31066253/53726328-2a23b100-3e87-11e9-96a8-ca2c4c98cee2.png)

iOS 12.1.1

**Comment by Nepeta** [comment]
New Snowboard update adds support for notifications.
