### ISSUE TITLE
“Details” doesn’t get themed icon or icon color as background. 

### ISSUE THREAD

**Issue by zyan910** [Nepeta/Notifica#14]
![bbb3be70-7608-4198-a3bb-8448467359bb](https://user-images.githubusercontent.com/31066253/53726461-6b1bc580-3e87-11e9-85f5-7dc19fef6506.png)

iOS 12.1.1

**Comment by Nepeta** [comment]
1. New Snowboard update should fix that.
2. It's an incompatibility issue with Noctis12.
