### ISSUE TITLE
[iOS 12.1.1] Notifications -> Background blur opacity issue

### ISSUE THREAD

**Issue by briancrink** [Nepeta/Notifica#6]
1. Adjust the background blur opacity between **0-25%** and press Test Notifications. 

2. Head to the lockscreen and you'll see background blur opacity only applies to the singular notifications and the _top_ notification in the collection of notifications.

This conclusion can be reached by noticing the notifications behind the top notification retain high opacity. When the background blur opacity is set to **0** (completely transparent), the text from the top notification appears off-center. 

To solve, the background blur opacity must be applied to _all_ notifications in the stack, not just the top notification.

[Test Notification Image](https://imgur.com/a/sPAfqzC)

**Comment by Nepeta** [comment]
Fixed in 0.1.6.

**Comment by briancrink** [comment]
> Fixed in 0.1.7.

Thank you! tested and works great, I'd contribute but I don't use bitcoin. If we cross paths, I'll buy ya a beer
