### ISSUE TITLE
Double notifications 

### ISSUE THREAD

**Issue by cartmancode** [Nepeta/Notifica#7]
Happenings on the reddit app v3.something.

**Comment by Nepeta** [comment]
Reddit app is broken. Use Apollo.

**Comment by cartmancode** [comment]
Not using that shit

**Comment by Nepeta** [comment]
🤷🏼‍♀️

Notifica can't cause double notifications and it's common knowledge that the official Reddit app is unbelievably broken.

**Comment by cartmancode** [comment]
Yes I am so sorry this is not an issue because of your nice tweak.

The darn app was fine on 11 but 12 has this bug, and it’s the only bug I suffer I think. It is a real shame because appolo I cant stand and as such refuse to pay for notifications. 

I hope someone helps out us silly reddit app user and drops a patch for this bug (hint hint).

Anyway sorry again and have a good night.
