### ISSUE TITLE
[iOS 12.1.2] Safe Mode if "Notifications"-section is disabled

### ISSUE THREAD

**Issue by gerrit-h** [Nepeta/Notifica#8]
My device always enters safe mode when receiving a notification.
Through trial & error i noticed that it only happens when the "Notifications"-section is disabled.

This crashlog is created by Cr4shed:
[2019-02-27_2358.log](https://github.com/Nepeta/Notifica/files/2912652/2019-02-27_2358.log)

Device: iPhone SE, iOS 12.1.2 (16C104)

**Comment by Nepeta** [comment]
That makes sense, thank you for the report.

**Comment by Nepeta** [comment]
Will be fixed in 0.1.5.
